// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import { config as loadEnv } from 'dotenv';
import { fileURLToPath } from 'node:url';
import { defineConfig, env } from 'prisma/config';

loadEnv({
	path: fileURLToPath(new URL('.env', import.meta.url))
});

export default defineConfig({
	schema: 'prisma/',
	migrations: {
		path: 'prisma/migrations'
	},
	datasource: {
		url: env('DATABASE_URL')
	}
});
